### PR TITLE
Update meow to v9 and devDependencies

### PR DESCRIPTION
**Pull request by dpdiliberto**
Updating dependencies to help resolve https://github.com/mapbox/polyline/issues/84. Per https://github.com/sindresorhus/meow/issues/204#issuecomment-1017609191, I updated meow to v9 rather than to the latest since later versions require ESM.

### CODE REVIEW

**Comment by dpdiliberto** [comment]
@tristen it looks like tests using Node 10 are failing, which I believe is due to the update to eslint. Do you think it would make sense to update `node_js` in https://github.com/mapbox/polyline/blob/master/.travis.yml to more recent versions?

**Comment by tristen** [comment]
@dpdiliberto that seems like a sensible change to me 👍. Maybe we can replace 10 and 12 with more recent 16 and 18 versions.

**Comment by dpdiliberto** [comment]
Thanks @tristen , I updated the Node versions, and also upgraded the Travis build environment (per https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/7), since I was running into the following build error:

```
$ nvm install 18
node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
The command "npm config set progress false" failed and exited with 1 during .
```

All checks are passing now 👍 .

**Review by tristen — APPROVED** [review]
Nice! Changes LGTM:

Screenshot 2023-09-13 at 3 10 22 PM

**Comment by leslieli** [comment]
Thanks @dpdiliberto and @tristen , please help publish a new release to NPM.

**Comment by tristen** [comment]
@leslieli done! https://www.npmjs.com/package/@mapbox/polyline/v/1.2.1

**Comment by leslieli** [comment]
Thanks @tristen .

**Comment by leslieli** [comment]
Looks upgrading the `meow` to v9 doesn't fix the issue https://github.com/mapbox/polyline/issues/84, it is still referencing the `semver@7.3.7`, not `v7.5.2`+
```
└─┬ @mapbox/polyline@1.2.1
  └─┬ meow@9.0.0
    ├─┬ normalize-package-data@3.0.3
    │ └── semver@7.3.7
    └─┬ read-pkg-up@7.0.1
      └─┬ read-pkg@5.2.0
        └─┬ normalize-package-data@2.5.0
          └── semver@5.7.1
```

**Comment by tristen** [comment]
👋 @leslieli want to put a pull request together that addresses the issue? I'd be happy to review and cut a new release.

**Comment by leslieli** [comment]
@tristen I am not quite familiar with the project and would like to suggest someone in your team could help on this. If possible, could you provide the estimation - when we can expect the fix release? Thanks.

**Pull request merged**
