### PR TITLE
Fixed issue with rounding coordinates

### PR DESCRIPTION
**Pull request by frederickjansen**
Coordinates should be rounded before calculating the offset

### CODE REVIEW

**Comment by frederickjansen** [comment]
Check [Google's polyline tool](https://developers.google.com/maps/documentation/utilities/polylineutility) for [[0, 0.000006], [0, 0.000002]]. The encoded polyline should be ?A?@, but this library returns ?A??

**Comment by frederickjansen** [comment]
@jfirebaugh Any chance this can get merged please?

**Comment by jfirebaugh** [comment]
@tmcw Can you take a look? I'm backed up on other commitments.

**Comment by tmcw** [comment]
Yep, looking into it now

**Comment by tmcw** [comment]
Well, I wrote an pretty cool test suite that compared the two javascript, python, and ruby, modules against authoritative results and confirmed this issue and also identified issues in several other libraries. And then I deleted it accidentally.

So I'm going to merge this and take a walk.

**Comment by frederickjansen** [comment]
@tmcw Thanks! Any chance the issues you noticed were present in https://github.com/frederickjansen/polyline? I maintain that library, so I'd like to keep it bug-free.

**Comment by tmcw** [comment]
Yes, there was a discrepancy where that library generated more points for the same line as Google. I'll redo the work at some point but am pretty discouraged.

**Comment by frederickjansen** [comment]
No worries, now I know and can do some research myself.

**Pull request merged**
